#!/bin/sh

CLANG=$(which clang)

if [ ! -e $CLANG ]; then
    exit
fi

input=""
if [ ! -t 0 ]; then
    input=$(cat)
fi

OFILE=`echo $* | sed -e 's/^.* \(.*\.o\) .*$/\\1/'`
if [ "x$OFILE" != x -a "$OFILE" != "$*" ] ; then
    if [ -z "${input}" ]; then
        $CLANG -emit-llvm -g "$@" >/dev/null 2>&1 > /dev/null
    else
        echo "${input}" | $CLANG -emit-llvm -g "$@" >/dev/null 2>&1 > /dev/null
    fi
    if [ -f "$OFILE" ] ; then
        BCFILE=`echo $OFILE | sed -e 's/o$/bc/'`
        #file $OFILE | grep -q "LLVM IR bitcode" && mv $OFILE $BCFILE || true
        if [ `file $OFILE | grep -c "LLVM IR bitcode"` -eq 1 ]; then
            mv $OFILE $BCFILE
        else
            touch $BCFILE
        fi
    fi
fi

if [ -z "${input}" ]; then
    exec $CLANG "$@"
else
    echo "$input" | exec $CLANG "$@"
fi  
